### ISSUE TITLE
API Support for Chargeback Flow

### ISSUE THREAD

**Issue by chessbyte** [ManageIQ/manageiq-api#781]
Even if no API changes are needed, would like to see an end-to-end working example of someone doing chargeback over the API.

- [x] ~~add endpoints for chargeback tiers, detail rates, measures~~ ->
  - ~~endpoint for read action~~
  - extend `api/rates` endpoint's create/edit action to pass chargeback tiers, detail rates, measures, chargeable_field (https://github.com/ManageIQ/manageiq-api/pull/847)
- [x] add endpoint for rate assignment (https://github.com/ManageIQ/manageiq-api/pull/824)
- [x] Support report results export functionality from the Rest API (https://github.com/ManageIQ/manageiq-api/issues/827)
- [x] fill default formatter instead of `nil` in `MiqReport#col_formats` (generally for all reports) (https://github.com/ManageIQ/manageiq/pull/20074)
- [x] [Issue - ManageIQ API: /api/reports returns null in col_formats, making UI hard to render](https://github.com/ManageIQ/manageiq-api/issues/797)
- [x] [Issue - ManageIQ API: /api/reports/:id/results/:id does not return unit in result_set](https://github.com/ManageIQ/manageiq-api/issues/798)
- [x] [Issue - ManageIQ API: /api/rates/:id only returns a compound version of rate definition](https://github.com/ManageIQ/manageiq-api/issues/800)
- [x] Docs + examples (https://github.com/ManageIQ/manageiq_docs/pull/1447)
  - Requesting report downloads - https://github.com/ManageIQ/manageiq_docs/pull/1446

**Various related fixes:**
- [x] https://github.com/ManageIQ/manageiq/pull/20078
- [x] https://github.com/ManageIQ/manageiq-api/pull/808
- [x] https://github.com/ManageIQ/manageiq/pull/20079

**Comment by lpichler** [comment]
it looks like that this covers areas:

- chargeback rates CRUD
- rate assignment 
- get chargeback output (chargeback report generation)
