### ISSUE TITLE
API Support for Compliance Policy Flow

### ISSUE THREAD

**Issue by chessbyte** [ManageIQ/manageiq-api#782]
Even if no API changes are needed, would like to see an end-to-end working example of someone doing compliance policies over the API.

---

- [x] [API Example](https://github.com/ManageIQ/manageiq_docs/pull/1390)
- [x] [Fix /api/vms/{id}/policies](https://github.com/ManageIQ/manageiq-api/issues/745)
- [x] [check_compliance Enhancement](https://github.com/ManageIQ/manageiq-api/issues/790)
- [ ] [~Include condition expression with compliance details response~](https://github.com/ManageIQ/manageiq-api/issues/838)

**Comment by abellotti** [comment]
wip documentation here: https://github.com/ManageIQ/manageiq_docs/pull/1390

**Comment by gtanzillo** [comment]
This is complete, will handle  [Include condition expression with compliance details response](https://github.com/ManageIQ/manageiq-api/issues/838) with a separate issue
