### ISSUE TITLE
API Performance

### ISSUE THREAD

**Issue by gtanzillo** [ManageIQ/manageiq-api#880]
Issues related to improving the performance of the ManageIQ Rest API

- [x] [Slow but small response for virtual columns seemingly due to N+1 queries](https://github.com/ManageIQ/manageiq-api/issues/869)
  - [x] _[renderer.rb] Don't re-Rbac: part deux:_  #874
  - [x] _AR VirtualAttribute queries + introspection:_ ~~#877~~ https://github.com/ManageIQ/manageiq-api/pull/887 https://github.com/ManageIQ/manageiq-api/pull/890
- [x] Improve user login timings
  - [x] ~~_Use~~ ~~`.update_attribute`~~ ~~over~~ ~~`.save!`~~ ~~for User login:_ ManageIQ/manageiq#20471~~
  - [x] Reduce queries for `User#save` validations:  https://github.com/ManageIQ/manageiq/pull/20590
- [x] [Add support for returning nil/null in associations](https://github.com/ManageIQ/manageiq-api/issues/870)
- [x] [Querying for `&attributes=hardware.cpu_sockets` is 0.5 seconds faster than `num_cpu`, WAT](https://github.com/ManageIQ/manageiq-api/issues/872)
