### ISSUE TITLE
API additions for Lasker

### ISSUE THREAD

**Issue by NickLaMuro** [ManageIQ/manageiq-api#977]
* [x] **[Subcollections::Results] Add DELETE actions** #975
* [x] **GET `/api contains available timezones`** - #973
* [x] **OPTIONS `/api/cloud_volumes?ems_id=:id`** - #914
* [x] **OPTIONS `/api/vm/:id/snapshots`** - #943
* [x] **GPPPD `/api/host_aggregates`** - #964
* [x] **GET `/api/shortcuts`** - #970
* [x] **PPPD `/api/floating_ips`** - #962
* [x] **PP `/api/network_routers`** - #960
* [x] **GET `/api/event_definition_sets`** - #954
* [x] **[Subcollection::Settings] Allow nested fetch** - #1004

**Comment by Fryguy** [comment]
@skateman Can you add your API PRs you've been working on?

**Comment by skateman** [comment]
[ ] `/api` should contain available timezones - https://github.com/ManageIQ/manageiq-api/pull/973
[ ] `OPTIONS /api/cloud_volumes?ems_id=:id` - https://github.com/ManageIQ/manageiq-api/pull/914
[ ] `OPTIONS /api/vm/:id/snapshots` - https://github.com/ManageIQ/manageiq-api/pull/943
[ ] `GPPPD /api/host_aggregates` - https://github.com/ManageIQ/manageiq-api/pull/964
[ ] `GET /api/shortcuts` - https://github.com/ManageIQ/manageiq-api/pull/970

**Comment by lpichler** [comment]
- [ ] GPPPD  `/app/widget_sets` widget_set https://github.com/ManageIQ/manageiq-api/pull/968
